import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import ClusterMan from './CM/clusterMan';

const inter = Inter({ subsets: ['latin'] });

export default function ClusterMain() {
  return (
    <>
      <Head>
        <title>Pod Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ClusterMan />
    </>
  );
}
