apiVersion: apps/v1
kind: Deployment
metadata:
  name: podwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podwatch
  template:
    metadata:
      labels:
        app: podwatch
    spec:
      containers:
        - name: podwatch
          image: wvaviator/podwatch:latest
          env:
            - name: PODWATCH_CLIENT_ID
              value: 'abc'
            - name: PODWATCH_CLIENT_SECRET
              value: '12345abcde'
      serviceAccountName: podwatch-serviceaccount
