import Head from 'next/head';
import Image from 'next/image';
import LandingContent from '@/components/LandingContent/LandingContent';
import logo from '/public/images/logo/512.png';
import LandingHeader from '../components/LandingHeader/LandingHeader';
import { Button } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pod Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <LandingContent heroImage={logo} heroImageAlt="Podwatch">
        <LandingHeader>
          <h1>PodWatch</h1>
          <h2>Kubernetes Error Hub</h2>
          <p>Streamline your Kubernetes monitoring with Pod Watch</p>
          <Button variant="contained" color="secondary">
            v0.0.1 Documentation
          </Button>
        </LandingHeader>
      </LandingContent>
    </>
  );
}
