import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import LandingContent from '@/components/LandingContent/LandingContent';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pod Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <LandingContent />
      </main>
    </>
  );
}
